import { type NextPage } from "next";
import Head from "next/head";
import { api } from "@/utils/api";
import { LoginButton } from "@/components/LoginButton";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>Apps</h1>
          {hello.data && <p>{hello.data.greeting}</p>}
          <LoginButton />
        </div>
      </main>
    </>
  );
};

export default Home;
