import { type NextPage } from "next";
import Head from "next/head";
import Navbar from "@/components/Navbar";
import { Box, Title } from "@mantine/core";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Prisma / NextAuth / tRPC</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
      </header>
      <main>
        <Box p="md">
          <Title order={1} align="center">
            Prisma / NextAuth / tRPC
          </Title>
        </Box>
      </main>
    </>
  );
};

export default Home;
